volumes:
  alloy:

networks:
  bogorintellitraffic:

services:
  web:
    build:
      context: .
      dockerfile: "./src/web/Dockerfile"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - "bogorintellitraffic"
    volumes:
      - "./data/database:/data/database:rw"
      - "./data/snapshots:/data/snapshots:rw"
      - "./data/dpkeys:/home/app/.aspnet/DataProtection-Keys:rw"
    env_file:
      - ".env"

  mediamtx:
    image: "bluenviron/mediamtx:1.12.2-ffmpeg"
    restart: unless-stopped
    expose:
      - "9998:9998"     # Prometheus
    ports:
      - "8888:8888"     # HLS
      - "8889:8889"     # WebRTC HTTP listener
      - "8189:8189/udp" # WebRTC UDP listener
    networks:
      - "bogorintellitraffic"
    volumes:
      - "./src/mediamtx/mediamtx.yml:/mediamtx.yml:ro"

  # nginx:
  #   build: "./src/reverse-proxy"
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   networks:
  #     - "bogorintellitraffic"
  
  alloy:
    image: grafana/alloy:v1.8.3
    restart: unless-stopped
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    networks:
    - "bogorintellitraffic"
    volumes:
      - "./src/grafana-alloy/config.alloy:/etc/alloy/config.alloy"
      - "alloy:/var/lib/alloy/data"
    env_file:
      - ".env"
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    restart: unless-stopped
    # pid: host
    # network_mode: host
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro      

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.52.1"
    restart: unless-stopped
    command:
      - '-port=9001'
    # network_mode: "host"
    privileged: true
    devices:
      - "/dev/kmsg"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"

